### ISSUE TITLE
Still looking for a maintainer?

### ISSUE THREAD

**Issue by jfrost** [procore/puppet-dnsmasq#3]
Myself and a few of my colleagues use this module and would love to help maintain it if you're still looking.

**Comment by javierbertoli** [comment]
Hey, @jfrost. Yes, that'd be great. Let me know how do you want to proceed.

**Comment by jfrost** [comment]
I guess the first question is do you want us to fork it to our own account or would you prefer we maintain it under the netmanagers account?

**Comment by javierbertoli** [comment]
On 12/08/2016 05:32 PM, Jeff Frost wrote:
> I guess the first question is do you want us to fork it to our own account or
> would you prefer we maintain it under the netmanagers account?

No need to, I'm totally OK you use your own account. I can either transfer you
the repo or you just fork it. The way you find more comfortable, I'm OK with it.

**Comment by jfrost** [comment]
I'm not seeing a LICENSE file in the repo. Am I just missing it?

**Comment by javierbertoli** [comment]
Forgot to add the file. [Added it](https://github.com/netmanagers/puppet-dnsmasq/blob/master/LICENSE)

**Comment by jfrost** [comment]
Awesome! Do you want to transfer it to the `procore` organization?

**Comment by javierbertoli** [comment]
Don't have permission to transfer the repo to your organization. Do you want me to add you temporarily to mine, or just go ahead with the fork and I delete this repo (I think this last option will discard one pending PR, though)?

**Comment by jfrost** [comment]
It would be great to hang onto the issues and PRs if we can. Perhaps the thing to do is contact github support?

**Comment by javierbertoli** [comment]
I transferred it to my account, was about to transfer it to yours so you can then transfer it to your organization (it seems that's the process). But you already have a repo named like this in your account. Mind you delete it (or provide me another member of your organization's account) so I can transfer it again?

**Comment by jfrost** [comment]
I bet I forked it to make a PR. Let me sort that out right quick!

**Comment by jfrost** [comment]
It is gone!

**Comment by javierbertoli** [comment]
Transferred.

**Comment by jfrost** [comment]
Got it successfully transferred into the procore org!
